puts "> Creating tags........"


Tag.create!([
  {title: "gamme", description: "", published: false, priority: 1},
  {title: "teuf friendly", description: "", published: false, priority: 2},
  {title: "pratique", description: "", published: false, priority: 3},
  {title: "original", description: "", published: false, priority: 4},
  {title: "expérience", description: "", published: false, priority: 5},
  {title: "décorabilité", description: "", published: false, priority: 6},
  {title: "alcoolisme", description: "", published: false, priority: 7},
  {title: "capacité", description: nil, published: nil, priority: 8},
  {title: "chic", description: "", published: false, priority: 9},
  {title: "dance", description: "", published: false, priority: 10},
  {title: "détails", description: nil, published: nil, priority: 11},
  {title: "luminosité", description: "", published: false, priority: 12},
  {title: "nature", description: "", published: false, priority: 13},
  {title: "trendy", description: "", published: false, priority: 14}
])
TagRating.create!([
  {tag_id: 22, tag_rating_group_id: 200, rating: 7},
  {tag_id: 22, tag_rating_group_id: 130, rating: 4},
  {tag_id: 22, tag_rating_group_id: 36, rating: 10},
  {tag_id: 22, tag_rating_group_id: 131, rating: 2},
  {tag_id: 22, tag_rating_group_id: 135, rating: 20},
  {tag_id: 22, tag_rating_group_id: 195, rating: 8},
  {tag_id: 22, tag_rating_group_id: 30, rating: 2},
  {tag_id: 22, tag_rating_group_id: 192, rating: 8},
  {tag_id: 22, tag_rating_group_id: 132, rating: 23},
  {tag_id: 22, tag_rating_group_id: 21, rating: 3},
  {tag_id: 22, tag_rating_group_id: 134, rating: 21},
  {tag_id: 22, tag_rating_group_id: 133, rating: 10},
  {tag_id: 22, tag_rating_group_id: 196, rating: 3},
  {tag_id: 22, tag_rating_group_id: 204, rating: 4},
  {tag_id: 22, tag_rating_group_id: 191, rating: 2},
  {tag_id: 22, tag_rating_group_id: 22, rating: 8},
  {tag_id: 22, tag_rating_group_id: 203, rating: 6},
  {tag_id: 22, tag_rating_group_id: 180, rating: 2},
  {tag_id: 22, tag_rating_group_id: 13, rating: 10},
  {tag_id: 22, tag_rating_group_id: 15, rating: 2},
  {tag_id: 22, tag_rating_group_id: 16, rating: 1},
  {tag_id: 22, tag_rating_group_id: 202, rating: 5},
  {tag_id: 22, tag_rating_group_id: 38, rating: 7},
  {tag_id: 22, tag_rating_group_id: 179, rating: 4},
  {tag_id: 22, tag_rating_group_id: 183, rating: 21},
  {tag_id: 22, tag_rating_group_id: 199, rating: 10},
  {tag_id: 22, tag_rating_group_id: 40, rating: 4},
  {tag_id: 22, tag_rating_group_id: 186, rating: 31},
  {tag_id: 22, tag_rating_group_id: 182, rating: 10},
  {tag_id: 22, tag_rating_group_id: 198, rating: 3},
  {tag_id: 22, tag_rating_group_id: 82, rating: 4},
  {tag_id: 22, tag_rating_group_id: 205, rating: 9},
  {tag_id: 22, tag_rating_group_id: 83, rating: 2},
  {tag_id: 22, tag_rating_group_id: 190, rating: 10},
  {tag_id: 22, tag_rating_group_id: 39, rating: 1},
  {tag_id: 22, tag_rating_group_id: 201, rating: 1},
  {tag_id: 22, tag_rating_group_id: 137, rating: 31},
  {tag_id: 22, tag_rating_group_id: 84, rating: 23},
  {tag_id: 22, tag_rating_group_id: 181, rating: 23},
  {tag_id: 22, tag_rating_group_id: 85, rating: 10},
  {tag_id: 22, tag_rating_group_id: 184, rating: 20},
  {tag_id: 22, tag_rating_group_id: 185, rating: 6},
  {tag_id: 22, tag_rating_group_id: 86, rating: 21},
  {tag_id: 22, tag_rating_group_id: 37, rating: 9},
  {tag_id: 22, tag_rating_group_id: 194, rating: 4},
  {tag_id: 22, tag_rating_group_id: 136, rating: 6},
  {tag_id: 22, tag_rating_group_id: 87, rating: 20},
  {tag_id: 22, tag_rating_group_id: 193, rating: 3},
  {tag_id: 22, tag_rating_group_id: 6, rating: 9},
  {tag_id: 22, tag_rating_group_id: 197, rating: 9},
  {tag_id: 22, tag_rating_group_id: 33, rating: 4},
  {tag_id: 35, tag_rating_group_id: 186, rating: 34},
  {tag_id: 35, tag_rating_group_id: 196, rating: 3},
  {tag_id: 35, tag_rating_group_id: 179, rating: 25},
  {tag_id: 35, tag_rating_group_id: 85, rating: 11},
  {tag_id: 35, tag_rating_group_id: 38, rating: 9},
  {tag_id: 35, tag_rating_group_id: 197, rating: 10},
  {tag_id: 35, tag_rating_group_id: 199, rating: 7},
  {tag_id: 35, tag_rating_group_id: 194, rating: 10},
  {tag_id: 35, tag_rating_group_id: 28, rating: 10},
  {tag_id: 35, tag_rating_group_id: 2, rating: 1},
  {tag_id: 35, tag_rating_group_id: 40, rating: 3},
  {tag_id: 35, tag_rating_group_id: 86, rating: 19},
  {tag_id: 35, tag_rating_group_id: 198, rating: 1},
  {tag_id: 35, tag_rating_group_id: 81, rating: 7},
  {tag_id: 35, tag_rating_group_id: 183, rating: 19},
  {tag_id: 35, tag_rating_group_id: 185, rating: 25},
  {tag_id: 35, tag_rating_group_id: 178, rating: 7},
  {tag_id: 35, tag_rating_group_id: 129, rating: 7},
  {tag_id: 35, tag_rating_group_id: 82, rating: 25},
  {tag_id: 35, tag_rating_group_id: 35, rating: 7},
  {tag_id: 35, tag_rating_group_id: 201, rating: 9},
  {tag_id: 35, tag_rating_group_id: 136, rating: 25},
  {tag_id: 35, tag_rating_group_id: 83, rating: 8},
  {tag_id: 35, tag_rating_group_id: 6, rating: 8},
  {tag_id: 35, tag_rating_group_id: 181, rating: 7},
  {tag_id: 35, tag_rating_group_id: 130, rating: 25},
  {tag_id: 35, tag_rating_group_id: 195, rating: 4},
  {tag_id: 35, tag_rating_group_id: 137, rating: 34},
  {tag_id: 35, tag_rating_group_id: 131, rating: 8},
  {tag_id: 35, tag_rating_group_id: 203, rating: 9},
  {tag_id: 35, tag_rating_group_id: 192, rating: 9},
  {tag_id: 35, tag_rating_group_id: 84, rating: 7},
  {tag_id: 35, tag_rating_group_id: 33, rating: 2},
  {tag_id: 35, tag_rating_group_id: 132, rating: 7},
  {tag_id: 35, tag_rating_group_id: 30, rating: 8},
  {tag_id: 35, tag_rating_group_id: 134, rating: 19},
  {tag_id: 35, tag_rating_group_id: 200, rating: 9},
  {tag_id: 35, tag_rating_group_id: 37, rating: 5},
  {tag_id: 35, tag_rating_group_id: 133, rating: 11},
  {tag_id: 35, tag_rating_group_id: 193, rating: 2},
  {tag_id: 35, tag_rating_group_id: 191, rating: 10},
  {tag_id: 35, tag_rating_group_id: 180, rating: 8},
  {tag_id: 35, tag_rating_group_id: 204, rating: 4},
  {tag_id: 35, tag_rating_group_id: 39, rating: 10},
  {tag_id: 35, tag_rating_group_id: 24, rating: 10},
  {tag_id: 35, tag_rating_group_id: 205, rating: 5},
  {tag_id: 35, tag_rating_group_id: 190, rating: 7},
  {tag_id: 35, tag_rating_group_id: 182, rating: 11},
  {tag_id: 35, tag_rating_group_id: 202, rating: 7},
  {tag_id: 21, tag_rating_group_id: 129, rating: 9},
  {tag_id: 21, tag_rating_group_id: 182, rating: 9},
  {tag_id: 21, tag_rating_group_id: 191, rating: 1},
  {tag_id: 21, tag_rating_group_id: 13, rating: 8},
  {tag_id: 21, tag_rating_group_id: 85, rating: 9},
  {tag_id: 21, tag_rating_group_id: 202, rating: 1},
  {tag_id: 21, tag_rating_group_id: 39, rating: 1},
  {tag_id: 21, tag_rating_group_id: 130, rating: 2},
  {tag_id: 21, tag_rating_group_id: 87, rating: 11},
  {tag_id: 21, tag_rating_group_id: 15, rating: 1},
  {tag_id: 21, tag_rating_group_id: 186, rating: 25},
  {tag_id: 21, tag_rating_group_id: 16, rating: 1},
  {tag_id: 21, tag_rating_group_id: 192, rating: 5},
  {tag_id: 21, tag_rating_group_id: 196, rating: 5},
  {tag_id: 21, tag_rating_group_id: 179, rating: 2},
  {tag_id: 21, tag_rating_group_id: 185, rating: 11},
  {tag_id: 21, tag_rating_group_id: 181, rating: 33},
  {tag_id: 21, tag_rating_group_id: 203, rating: 6},
  {tag_id: 21, tag_rating_group_id: 197, rating: 3},
  {tag_id: 21, tag_rating_group_id: 199, rating: 9},
  {tag_id: 21, tag_rating_group_id: 195, rating: 10},
  {tag_id: 21, tag_rating_group_id: 37, rating: 9},
  {tag_id: 21, tag_rating_group_id: 194, rating: 1},
  {tag_id: 21, tag_rating_group_id: 86, rating: 2},
  {tag_id: 21, tag_rating_group_id: 29, rating: 2},
  {tag_id: 21, tag_rating_group_id: 131, rating: 4},
  {tag_id: 21, tag_rating_group_id: 190, rating: 9},
  {tag_id: 21, tag_rating_group_id: 81, rating: 9},
  {tag_id: 21, tag_rating_group_id: 40, rating: 4},
  {tag_id: 21, tag_rating_group_id: 193, rating: 3},
  {tag_id: 21, tag_rating_group_id: 38, rating: 6},
  {tag_id: 21, tag_rating_group_id: 18, rating: 9},
  {tag_id: 21, tag_rating_group_id: 183, rating: 2},
  {tag_id: 21, tag_rating_group_id: 198, rating: 1},
  {tag_id: 21, tag_rating_group_id: 180, rating: 4},
  {tag_id: 21, tag_rating_group_id: 84, rating: 33},
  {tag_id: 21, tag_rating_group_id: 204, rating: 4},
  {tag_id: 21, tag_rating_group_id: 135, rating: 11},
  {tag_id: 21, tag_rating_group_id: 82, rating: 2},
  {tag_id: 21, tag_rating_group_id: 136, rating: 11},
  {tag_id: 21, tag_rating_group_id: 137, rating: 25},
  {tag_id: 21, tag_rating_group_id: 133, rating: 9},
  {tag_id: 21, tag_rating_group_id: 178, rating: 9},
  {tag_id: 21, tag_rating_group_id: 132, rating: 33},
  {tag_id: 21, tag_rating_group_id: 205, rating: 10},
  {tag_id: 21, tag_rating_group_id: 201, rating: 5},
  {tag_id: 21, tag_rating_group_id: 83, rating: 4},
  {tag_id: 21, tag_rating_group_id: 184, rating: 11},
  {tag_id: 21, tag_rating_group_id: 200, rating: 4},
  {tag_id: 21, tag_rating_group_id: 134, rating: 2},
  {tag_id: 21, tag_rating_group_id: 1, rating: 6},
  {tag_id: 3, tag_rating_group_id: 201, rating: 8},
  {tag_id: 3, tag_rating_group_id: 182, rating: 48},
  {tag_id: 3, tag_rating_group_id: 186, rating: 10},
  {tag_id: 3, tag_rating_group_id: 183, rating: 16},
  {tag_id: 3, tag_rating_group_id: 185, rating: 7},
  {tag_id: 3, tag_rating_group_id: 184, rating: 13},
  {tag_id: 3, tag_rating_group_id: 29, rating: 10},
  {tag_id: 3, tag_rating_group_id: 203, rating: 5},
  {tag_id: 3, tag_rating_group_id: 205, rating: 4},
  {tag_id: 3, tag_rating_group_id: 32, rating: 9},
  {tag_id: 3, tag_rating_group_id: 14, rating: 7},
  {tag_id: 3, tag_rating_group_id: 202, rating: 9},
  {tag_id: 3, tag_rating_group_id: 26, rating: 8},
  {tag_id: 3, tag_rating_group_id: 199, rating: 4},
  {tag_id: 3, tag_rating_group_id: 81, rating: 14},
  {tag_id: 3, tag_rating_group_id: 4, rating: 10},
  {tag_id: 3, tag_rating_group_id: 3, rating: 7},
  {tag_id: 3, tag_rating_group_id: 198, rating: 5},
  {tag_id: 3, tag_rating_group_id: 82, rating: 19},
  {tag_id: 3, tag_rating_group_id: 83, rating: 29},
  {tag_id: 3, tag_rating_group_id: 84, rating: 27},
  {tag_id: 3, tag_rating_group_id: 85, rating: 48},
  {tag_id: 3, tag_rating_group_id: 200, rating: 9},
  {tag_id: 3, tag_rating_group_id: 19, rating: 9},
  {tag_id: 3, tag_rating_group_id: 196, rating: 2},
  {tag_id: 3, tag_rating_group_id: 86, rating: 16},
  {tag_id: 3, tag_rating_group_id: 194, rating: 10},
  {tag_id: 3, tag_rating_group_id: 87, rating: 13},
  {tag_id: 3, tag_rating_group_id: 129, rating: 21},
  {tag_id: 3, tag_rating_group_id: 197, rating: 6},
  {tag_id: 3, tag_rating_group_id: 130, rating: 19},
  {tag_id: 3, tag_rating_group_id: 191, rating: 10},
  {tag_id: 3, tag_rating_group_id: 131, rating: 29},
  {tag_id: 3, tag_rating_group_id: 195, rating: 2},
  {tag_id: 3, tag_rating_group_id: 36, rating: 6},
  {tag_id: 3, tag_rating_group_id: 132, rating: 27},
  {tag_id: 3, tag_rating_group_id: 204, rating: 2},
  {tag_id: 3, tag_rating_group_id: 192, rating: 7},
  {tag_id: 3, tag_rating_group_id: 133, rating: 48},
  {tag_id: 3, tag_rating_group_id: 134, rating: 16},
  {tag_id: 3, tag_rating_group_id: 135, rating: 13},
  {tag_id: 3, tag_rating_group_id: 136, rating: 7},
  {tag_id: 3, tag_rating_group_id: 193, rating: 2},
  {tag_id: 3, tag_rating_group_id: 1, rating: 8},
  {tag_id: 3, tag_rating_group_id: 137, rating: 10},
  {tag_id: 3, tag_rating_group_id: 190, rating: 4},
  {tag_id: 3, tag_rating_group_id: 178, rating: 21},
  {tag_id: 3, tag_rating_group_id: 7, rating: 9},
  {tag_id: 3, tag_rating_group_id: 179, rating: 19},
  {tag_id: 3, tag_rating_group_id: 38, rating: 7},
  {tag_id: 3, tag_rating_group_id: 2, rating: 10},
  {tag_id: 3, tag_rating_group_id: 180, rating: 29},
  {tag_id: 3, tag_rating_group_id: 181, rating: 27},
  {tag_id: 3, tag_rating_group_id: 39, rating: 10},
  {tag_id: 31, tag_rating_group_id: 131, rating: 19},
  {tag_id: 31, tag_rating_group_id: 184, rating: 9},
  {tag_id: 31, tag_rating_group_id: 83, rating: 19},
  {tag_id: 31, tag_rating_group_id: 178, rating: 29},
  {tag_id: 31, tag_rating_group_id: 190, rating: 5},
  {tag_id: 31, tag_rating_group_id: 181, rating: 10},
  {tag_id: 31, tag_rating_group_id: 198, rating: 10},
  {tag_id: 31, tag_rating_group_id: 81, rating: 29},
  {tag_id: 31, tag_rating_group_id: 199, rating: 8},
  {tag_id: 31, tag_rating_group_id: 202, rating: 8},
  {tag_id: 31, tag_rating_group_id: 14, rating: 10},
  {tag_id: 31, tag_rating_group_id: 5, rating: 10},
  {tag_id: 31, tag_rating_group_id: 182, rating: 20},
  {tag_id: 31, tag_rating_group_id: 180, rating: 19},
  {tag_id: 31, tag_rating_group_id: 203, rating: 4},
  {tag_id: 31, tag_rating_group_id: 23, rating: 9},
  {tag_id: 31, tag_rating_group_id: 196, rating: 4},
  {tag_id: 31, tag_rating_group_id: 191, rating: 9},
  {tag_id: 31, tag_rating_group_id: 133, rating: 20},
  {tag_id: 31, tag_rating_group_id: 200, rating: 7},
  {tag_id: 31, tag_rating_group_id: 132, rating: 10},
  {tag_id: 31, tag_rating_group_id: 192, rating: 8},
  {tag_id: 31, tag_rating_group_id: 195, rating: 2},
  {tag_id: 31, tag_rating_group_id: 135, rating: 9},
  {tag_id: 31, tag_rating_group_id: 197, rating: 8},
  {tag_id: 31, tag_rating_group_id: 129, rating: 29},
  {tag_id: 31, tag_rating_group_id: 22, rating: 9},
  {tag_id: 31, tag_rating_group_id: 29, rating: 10},
  {tag_id: 31, tag_rating_group_id: 87, rating: 9},
  {tag_id: 31, tag_rating_group_id: 136, rating: 10},
  {tag_id: 31, tag_rating_group_id: 194, rating: 10},
  {tag_id: 31, tag_rating_group_id: 185, rating: 10},
  {tag_id: 31, tag_rating_group_id: 193, rating: 10},
  {tag_id: 31, tag_rating_group_id: 85, rating: 20},
  {tag_id: 31, tag_rating_group_id: 84, rating: 10},
  {tag_id: 31, tag_rating_group_id: 201, rating: 5},
  {tag_id: 31, tag_rating_group_id: 204, rating: 5},
  {tag_id: 31, tag_rating_group_id: 205, rating: 4},
  {tag_id: 34, tag_rating_group_id: 135, rating: 8},
  {tag_id: 34, tag_rating_group_id: 197, rating: 5},
  {tag_id: 34, tag_rating_group_id: 39, rating: 10},
  {tag_id: 34, tag_rating_group_id: 192, rating: 8},
  {tag_id: 34, tag_rating_group_id: 191, rating: 10},
  {tag_id: 34, tag_rating_group_id: 190, rating: 2},
  {tag_id: 34, tag_rating_group_id: 87, rating: 8},
  {tag_id: 34, tag_rating_group_id: 203, rating: 5},
  {tag_id: 34, tag_rating_group_id: 194, rating: 10},
  {tag_id: 34, tag_rating_group_id: 198, rating: 7},
  {tag_id: 34, tag_rating_group_id: 195, rating: 3},
  {tag_id: 34, tag_rating_group_id: 200, rating: 9},
  {tag_id: 34, tag_rating_group_id: 184, rating: 8},
  {tag_id: 34, tag_rating_group_id: 193, rating: 4},
  {tag_id: 34, tag_rating_group_id: 37, rating: 10},
  {tag_id: 34, tag_rating_group_id: 199, rating: 4},
  {tag_id: 34, tag_rating_group_id: 205, rating: 2},
  {tag_id: 34, tag_rating_group_id: 22, rating: 8},
  {tag_id: 34, tag_rating_group_id: 201, rating: 7},
  {tag_id: 34, tag_rating_group_id: 27, rating: 8},
  {tag_id: 34, tag_rating_group_id: 202, rating: 9},
  {tag_id: 34, tag_rating_group_id: 204, rating: 3},
  {tag_id: 34, tag_rating_group_id: 196, rating: 5},
  {tag_id: 37, tag_rating_group_id: 199, rating: 7},
  {tag_id: 37, tag_rating_group_id: 17, rating: 8},
  {tag_id: 37, tag_rating_group_id: 1, rating: 9},
  {tag_id: 37, tag_rating_group_id: 6, rating: 10},
  {tag_id: 37, tag_rating_group_id: 24, rating: 10},
  {tag_id: 37, tag_rating_group_id: 31, rating: 9},
  {tag_id: 37, tag_rating_group_id: 81, rating: 9},
  {tag_id: 37, tag_rating_group_id: 82, rating: 18},
  {tag_id: 37, tag_rating_group_id: 83, rating: 8},
  {tag_id: 37, tag_rating_group_id: 84, rating: 9},
  {tag_id: 37, tag_rating_group_id: 85, rating: 10},
  {tag_id: 37, tag_rating_group_id: 86, rating: 37},
  {tag_id: 37, tag_rating_group_id: 87, rating: 9},
  {tag_id: 37, tag_rating_group_id: 129, rating: 9},
  {tag_id: 37, tag_rating_group_id: 130, rating: 18},
  {tag_id: 37, tag_rating_group_id: 131, rating: 8},
  {tag_id: 37, tag_rating_group_id: 132, rating: 9},
  {tag_id: 37, tag_rating_group_id: 133, rating: 10},
  {tag_id: 37, tag_rating_group_id: 134, rating: 37},
  {tag_id: 37, tag_rating_group_id: 135, rating: 9},
  {tag_id: 37, tag_rating_group_id: 136, rating: 10},
  {tag_id: 37, tag_rating_group_id: 137, rating: 20},
  {tag_id: 37, tag_rating_group_id: 178, rating: 9},
  {tag_id: 37, tag_rating_group_id: 179, rating: 18},
  {tag_id: 37, tag_rating_group_id: 180, rating: 8},
  {tag_id: 37, tag_rating_group_id: 181, rating: 9},
  {tag_id: 37, tag_rating_group_id: 182, rating: 10},
  {tag_id: 37, tag_rating_group_id: 183, rating: 37},
  {tag_id: 37, tag_rating_group_id: 184, rating: 9},
  {tag_id: 37, tag_rating_group_id: 185, rating: 10},
  {tag_id: 37, tag_rating_group_id: 186, rating: 20},
  {tag_id: 37, tag_rating_group_id: 38, rating: 9},
  {tag_id: 37, tag_rating_group_id: 40, rating: 3},
  {tag_id: 37, tag_rating_group_id: 192, rating: 10},
  {tag_id: 37, tag_rating_group_id: 190, rating: 7},
  {tag_id: 37, tag_rating_group_id: 193, rating: 2},
  {tag_id: 37, tag_rating_group_id: 191, rating: 10},
  {tag_id: 37, tag_rating_group_id: 194, rating: 10},
  {tag_id: 37, tag_rating_group_id: 196, rating: 4},
  {tag_id: 37, tag_rating_group_id: 200, rating: 10},
  {tag_id: 37, tag_rating_group_id: 195, rating: 5},
  {tag_id: 37, tag_rating_group_id: 197, rating: 10},
  {tag_id: 37, tag_rating_group_id: 201, rating: 9},
  {tag_id: 37, tag_rating_group_id: 198, rating: 2},
  {tag_id: 37, tag_rating_group_id: 202, rating: 9},
  {tag_id: 37, tag_rating_group_id: 203, rating: 10},
  {tag_id: 37, tag_rating_group_id: 204, rating: 4},
  {tag_id: 37, tag_rating_group_id: 205, rating: 6},
  {tag_id: 40, tag_rating_group_id: 201, rating: 3},
  {tag_id: 40, tag_rating_group_id: 199, rating: 9},
  {tag_id: 40, tag_rating_group_id: 194, rating: 10},
  {tag_id: 40, tag_rating_group_id: 195, rating: 6},
  {tag_id: 40, tag_rating_group_id: 196, rating: 7},
  {tag_id: 40, tag_rating_group_id: 198, rating: 3},
  {tag_id: 40, tag_rating_group_id: 191, rating: 10},
  {tag_id: 40, tag_rating_group_id: 197, rating: 8},
  {tag_id: 40, tag_rating_group_id: 205, rating: 7},
  {tag_id: 40, tag_rating_group_id: 190, rating: 10},
  {tag_id: 40, tag_rating_group_id: 202, rating: 10},
  {tag_id: 40, tag_rating_group_id: 203, rating: 5},
  {tag_id: 40, tag_rating_group_id: 192, rating: 10},
  {tag_id: 40, tag_rating_group_id: 193, rating: 3},
  {tag_id: 40, tag_rating_group_id: 204, rating: 6},
  {tag_id: 40, tag_rating_group_id: 200, rating: 8},
  {tag_id: 2, tag_rating_group_id: 182, rating: 9},
  {tag_id: 2, tag_rating_group_id: 18, rating: 9},
  {tag_id: 2, tag_rating_group_id: 87, rating: 19},
  {tag_id: 2, tag_rating_group_id: 185, rating: 27},
  {tag_id: 2, tag_rating_group_id: 83, rating: 18},
  {tag_id: 2, tag_rating_group_id: 84, rating: 33},
  {tag_id: 2, tag_rating_group_id: 86, rating: 7},
  {tag_id: 2, tag_rating_group_id: 34, rating: 10},
  {tag_id: 2, tag_rating_group_id: 201, rating: 1},
  {tag_id: 2, tag_rating_group_id: 85, rating: 9},
  {tag_id: 2, tag_rating_group_id: 35, rating: 8},
  {tag_id: 2, tag_rating_group_id: 183, rating: 7},
  {tag_id: 2, tag_rating_group_id: 179, rating: 8},
  {tag_id: 2, tag_rating_group_id: 6, rating: 7},
  {tag_id: 2, tag_rating_group_id: 190, rating: 10},
  {tag_id: 2, tag_rating_group_id: 204, rating: 3},
  {tag_id: 2, tag_rating_group_id: 178, rating: 27},
  {tag_id: 2, tag_rating_group_id: 205, rating: 7},
  {tag_id: 2, tag_rating_group_id: 193, rating: 4},
  {tag_id: 2, tag_rating_group_id: 137, rating: 40},
  {tag_id: 2, tag_rating_group_id: 22, rating: 10},
  {tag_id: 2, tag_rating_group_id: 23, rating: 10},
  {tag_id: 2, tag_rating_group_id: 136, rating: 27},
  {tag_id: 2, tag_rating_group_id: 192, rating: 6},
  {tag_id: 2, tag_rating_group_id: 203, rating: 5},
  {tag_id: 2, tag_rating_group_id: 135, rating: 19},
  {tag_id: 2, tag_rating_group_id: 191, rating: 1},
  {tag_id: 2, tag_rating_group_id: 13, rating: 8},
  {tag_id: 2, tag_rating_group_id: 196, rating: 2},
  {tag_id: 2, tag_rating_group_id: 134, rating: 7},
  {tag_id: 2, tag_rating_group_id: 181, rating: 33},
  {tag_id: 2, tag_rating_group_id: 186, rating: 40},
  {tag_id: 2, tag_rating_group_id: 202, rating: 6},
  {tag_id: 2, tag_rating_group_id: 200, rating: 9},
  {tag_id: 2, tag_rating_group_id: 133, rating: 9},
  {tag_id: 2, tag_rating_group_id: 27, rating: 9},
  {tag_id: 2, tag_rating_group_id: 5, rating: 10},
  {tag_id: 2, tag_rating_group_id: 195, rating: 9},
  {tag_id: 2, tag_rating_group_id: 37, rating: 10},
  {tag_id: 2, tag_rating_group_id: 132, rating: 33},
  {tag_id: 2, tag_rating_group_id: 81, rating: 37},
  {tag_id: 2, tag_rating_group_id: 184, rating: 19},
  {tag_id: 2, tag_rating_group_id: 131, rating: 18},
  {tag_id: 2, tag_rating_group_id: 199, rating: 10},
  {tag_id: 2, tag_rating_group_id: 130, rating: 8},
  {tag_id: 2, tag_rating_group_id: 82, rating: 8},
  {tag_id: 2, tag_rating_group_id: 180, rating: 18},
  {tag_id: 2, tag_rating_group_id: 197, rating: 6},
  {tag_id: 2, tag_rating_group_id: 129, rating: 27},
  {tag_id: 2, tag_rating_group_id: 198, rating: 3},
  {tag_id: 2, tag_rating_group_id: 194, rating: 2},
  {tag_id: 6, tag_rating_group_id: 134, rating: 8},
  {tag_id: 6, tag_rating_group_id: 25, rating: 9},
  {tag_id: 6, tag_rating_group_id: 181, rating: 25},
  {tag_id: 6, tag_rating_group_id: 82, rating: 8},
  {tag_id: 6, tag_rating_group_id: 136, rating: 15},
  {tag_id: 6, tag_rating_group_id: 183, rating: 8},
  {tag_id: 6, tag_rating_group_id: 24, rating: 8},
  {tag_id: 6, tag_rating_group_id: 203, rating: 7},
  {tag_id: 6, tag_rating_group_id: 204, rating: 4},
  {tag_id: 6, tag_rating_group_id: 184, rating: 7},
  {tag_id: 6, tag_rating_group_id: 192, rating: 9},
  {tag_id: 6, tag_rating_group_id: 135, rating: 7},
  {tag_id: 6, tag_rating_group_id: 129, rating: 7},
  {tag_id: 6, tag_rating_group_id: 186, rating: 15},
  {tag_id: 6, tag_rating_group_id: 190, rating: 6},
  {tag_id: 6, tag_rating_group_id: 205, rating: 5},
  {tag_id: 6, tag_rating_group_id: 199, rating: 7},
  {tag_id: 6, tag_rating_group_id: 191, rating: 9},
  {tag_id: 6, tag_rating_group_id: 185, rating: 15},
  {tag_id: 6, tag_rating_group_id: 26, rating: 8},
  {tag_id: 6, tag_rating_group_id: 179, rating: 8},
  {tag_id: 6, tag_rating_group_id: 196, rating: 2},
  {tag_id: 6, tag_rating_group_id: 84, rating: 25},
  {tag_id: 6, tag_rating_group_id: 202, rating: 7},
  {tag_id: 6, tag_rating_group_id: 130, rating: 8},
  {tag_id: 6, tag_rating_group_id: 81, rating: 7},
  {tag_id: 6, tag_rating_group_id: 198, rating: 3},
  {tag_id: 6, tag_rating_group_id: 18, rating: 7},
  {tag_id: 6, tag_rating_group_id: 1, rating: 10},
  {tag_id: 6, tag_rating_group_id: 200, rating: 9},
  {tag_id: 6, tag_rating_group_id: 133, rating: 15},
  {tag_id: 6, tag_rating_group_id: 85, rating: 15},
  {tag_id: 6, tag_rating_group_id: 194, rating: 8},
  {tag_id: 6, tag_rating_group_id: 132, rating: 25},
  {tag_id: 6, tag_rating_group_id: 178, rating: 7},
  {tag_id: 6, tag_rating_group_id: 87, rating: 7},
  {tag_id: 6, tag_rating_group_id: 86, rating: 8},
  {tag_id: 6, tag_rating_group_id: 28, rating: 4},
  {tag_id: 6, tag_rating_group_id: 137, rating: 15},
  {tag_id: 6, tag_rating_group_id: 182, rating: 15},
  {tag_id: 6, tag_rating_group_id: 21, rating: 8},
  {tag_id: 6, tag_rating_group_id: 201, rating: 8},
  {tag_id: 6, tag_rating_group_id: 197, rating: 10},
  {tag_id: 6, tag_rating_group_id: 193, rating: 3},
  {tag_id: 6, tag_rating_group_id: 195, rating: 6},
  {tag_id: 41, tag_rating_group_id: 202, rating: 5},
  {tag_id: 41, tag_rating_group_id: 192, rating: 10},
  {tag_id: 41, tag_rating_group_id: 205, rating: 5},
  {tag_id: 41, tag_rating_group_id: 200, rating: 8},
  {tag_id: 41, tag_rating_group_id: 198, rating: 2},
  {tag_id: 41, tag_rating_group_id: 204, rating: 2},
  {tag_id: 41, tag_rating_group_id: 195, rating: 3},
  {tag_id: 41, tag_rating_group_id: 196, rating: 3},
  {tag_id: 41, tag_rating_group_id: 201, rating: 5},
  {tag_id: 41, tag_rating_group_id: 190, rating: 7},
  {tag_id: 41, tag_rating_group_id: 199, rating: 10},
  {tag_id: 41, tag_rating_group_id: 197, rating: 6},
  {tag_id: 41, tag_rating_group_id: 203, rating: 5},
  {tag_id: 41, tag_rating_group_id: 193, rating: 1},
  {tag_id: 41, tag_rating_group_id: 194, rating: 7},
  {tag_id: 41, tag_rating_group_id: 191, rating: 9},
  {tag_id: 33, tag_rating_group_id: 199, rating: 7},
  {tag_id: 33, tag_rating_group_id: 37, rating: 8},
  {tag_id: 33, tag_rating_group_id: 182, rating: 20},
  {tag_id: 33, tag_rating_group_id: 40, rating: 10},
  {tag_id: 33, tag_rating_group_id: 178, rating: 20},
  {tag_id: 33, tag_rating_group_id: 190, rating: 8},
  {tag_id: 33, tag_rating_group_id: 193, rating: 10},
  {tag_id: 33, tag_rating_group_id: 192, rating: 5},
  {tag_id: 33, tag_rating_group_id: 191, rating: 3},
  {tag_id: 33, tag_rating_group_id: 133, rating: 20},
  {tag_id: 33, tag_rating_group_id: 196, rating: 6},
  {tag_id: 33, tag_rating_group_id: 195, rating: 8},
  {tag_id: 33, tag_rating_group_id: 205, rating: 5},
  {tag_id: 33, tag_rating_group_id: 129, rating: 20},
  {tag_id: 33, tag_rating_group_id: 197, rating: 5},
  {tag_id: 33, tag_rating_group_id: 194, rating: 7},
  {tag_id: 33, tag_rating_group_id: 85, rating: 20},
  {tag_id: 33, tag_rating_group_id: 200, rating: 5},
  {tag_id: 33, tag_rating_group_id: 201, rating: 5},
  {tag_id: 33, tag_rating_group_id: 198, rating: 10},
  {tag_id: 33, tag_rating_group_id: 81, rating: 20},
  {tag_id: 33, tag_rating_group_id: 202, rating: 5},
  {tag_id: 33, tag_rating_group_id: 14, rating: 10},
  {tag_id: 33, tag_rating_group_id: 203, rating: 5},
  {tag_id: 33, tag_rating_group_id: 204, rating: 5},
  {tag_id: 4, tag_rating_group_id: 40, rating: 10},
  {tag_id: 4, tag_rating_group_id: 86, rating: 27},
  {tag_id: 4, tag_rating_group_id: 84, rating: 8},
  {tag_id: 4, tag_rating_group_id: 181, rating: 8},
  {tag_id: 4, tag_rating_group_id: 201, rating: 5},
  {tag_id: 4, tag_rating_group_id: 83, rating: 28},
  {tag_id: 4, tag_rating_group_id: 194, rating: 9},
  {tag_id: 4, tag_rating_group_id: 87, rating: 27},
  {tag_id: 4, tag_rating_group_id: 129, rating: 7},
  {tag_id: 4, tag_rating_group_id: 197, rating: 5},
  {tag_id: 4, tag_rating_group_id: 82, rating: 35},
  {tag_id: 4, tag_rating_group_id: 183, rating: 27},
  {tag_id: 4, tag_rating_group_id: 198, rating: 10},
  {tag_id: 4, tag_rating_group_id: 186, rating: 7},
  {tag_id: 4, tag_rating_group_id: 130, rating: 35},
  {tag_id: 4, tag_rating_group_id: 131, rating: 28},
  {tag_id: 4, tag_rating_group_id: 81, rating: 7},
  {tag_id: 4, tag_rating_group_id: 195, rating: 1},
  {tag_id: 4, tag_rating_group_id: 132, rating: 8},
  {tag_id: 4, tag_rating_group_id: 199, rating: 4},
  {tag_id: 4, tag_rating_group_id: 133, rating: 8},
  {tag_id: 4, tag_rating_group_id: 196, rating: 8},
  {tag_id: 4, tag_rating_group_id: 20, rating: 10},
  {tag_id: 4, tag_rating_group_id: 191, rating: 5},
  {tag_id: 4, tag_rating_group_id: 134, rating: 27},
  {tag_id: 4, tag_rating_group_id: 25, rating: 7},
  {tag_id: 4, tag_rating_group_id: 202, rating: 5},
  {tag_id: 4, tag_rating_group_id: 16, rating: 10},
  {tag_id: 4, tag_rating_group_id: 182, rating: 8},
  {tag_id: 4, tag_rating_group_id: 7, rating: 8},
  {tag_id: 4, tag_rating_group_id: 192, rating: 4},
  {tag_id: 4, tag_rating_group_id: 135, rating: 27},
  {tag_id: 4, tag_rating_group_id: 31, rating: 7},
  {tag_id: 4, tag_rating_group_id: 136, rating: 7},
  {tag_id: 4, tag_rating_group_id: 193, rating: 10},
  {tag_id: 4, tag_rating_group_id: 203, rating: 4},
  {tag_id: 4, tag_rating_group_id: 30, rating: 7},
  {tag_id: 4, tag_rating_group_id: 137, rating: 7},
  {tag_id: 4, tag_rating_group_id: 190, rating: 3},
  {tag_id: 4, tag_rating_group_id: 178, rating: 7},
  {tag_id: 4, tag_rating_group_id: 33, rating: 10},
  {tag_id: 4, tag_rating_group_id: 204, rating: 7},
  {tag_id: 4, tag_rating_group_id: 179, rating: 35},
  {tag_id: 4, tag_rating_group_id: 184, rating: 27},
  {tag_id: 4, tag_rating_group_id: 185, rating: 7},
  {tag_id: 4, tag_rating_group_id: 180, rating: 28},
  {tag_id: 4, tag_rating_group_id: 85, rating: 8},
  {tag_id: 4, tag_rating_group_id: 205, rating: 4},
  {tag_id: 4, tag_rating_group_id: 200, rating: 4},
  {tag_id: 1, tag_rating_group_id: 87, rating: 7},
  {tag_id: 1, tag_rating_group_id: 186, rating: 16},
  {tag_id: 1, tag_rating_group_id: 135, rating: 7},
  {tag_id: 1, tag_rating_group_id: 84, rating: 16},
  {tag_id: 1, tag_rating_group_id: 202, rating: 4},
  {tag_id: 1, tag_rating_group_id: 180, rating: 19},
  {tag_id: 1, tag_rating_group_id: 201, rating: 3},
  {tag_id: 1, tag_rating_group_id: 38, rating: 10},
  {tag_id: 1, tag_rating_group_id: 197, rating: 10},
  {tag_id: 1, tag_rating_group_id: 129, rating: 16},
  {tag_id: 1, tag_rating_group_id: 204, rating: 4},
  {tag_id: 1, tag_rating_group_id: 83, rating: 19},
  {tag_id: 1, tag_rating_group_id: 193, rating: 2},
  {tag_id: 1, tag_rating_group_id: 130, rating: 19},
  {tag_id: 1, tag_rating_group_id: 86, rating: 10},
  {tag_id: 1, tag_rating_group_id: 136, rating: 16},
  {tag_id: 1, tag_rating_group_id: 184, rating: 7},
  {tag_id: 1, tag_rating_group_id: 191, rating: 2},
  {tag_id: 1, tag_rating_group_id: 82, rating: 19},
  {tag_id: 1, tag_rating_group_id: 85, rating: 7},
  {tag_id: 1, tag_rating_group_id: 198, rating: 5},
  {tag_id: 1, tag_rating_group_id: 182, rating: 7},
  {tag_id: 1, tag_rating_group_id: 195, rating: 9},
  {tag_id: 1, tag_rating_group_id: 131, rating: 19},
  {tag_id: 1, tag_rating_group_id: 200, rating: 10},
  {tag_id: 1, tag_rating_group_id: 137, rating: 16},
  {tag_id: 1, tag_rating_group_id: 190, rating: 5},
  {tag_id: 1, tag_rating_group_id: 132, rating: 16},
  {tag_id: 1, tag_rating_group_id: 81, rating: 16},
  {tag_id: 1, tag_rating_group_id: 179, rating: 19},
  {tag_id: 1, tag_rating_group_id: 203, rating: 9},
  {tag_id: 1, tag_rating_group_id: 18, rating: 7},
  {tag_id: 1, tag_rating_group_id: 192, rating: 10},
  {tag_id: 1, tag_rating_group_id: 133, rating: 7},
  {tag_id: 1, tag_rating_group_id: 199, rating: 7},
  {tag_id: 1, tag_rating_group_id: 17, rating: 10},
  {tag_id: 1, tag_rating_group_id: 205, rating: 8},
  {tag_id: 1, tag_rating_group_id: 196, rating: 2},
  {tag_id: 1, tag_rating_group_id: 134, rating: 10},
  {tag_id: 1, tag_rating_group_id: 183, rating: 10},
  {tag_id: 1, tag_rating_group_id: 185, rating: 16},
  {tag_id: 1, tag_rating_group_id: 39, rating: 9},
  {tag_id: 1, tag_rating_group_id: 178, rating: 16},
  {tag_id: 1, tag_rating_group_id: 181, rating: 16},
  {tag_id: 1, tag_rating_group_id: 194, rating: 6},
  {tag_id: 1, tag_rating_group_id: 35, rating: 9}
])
TagRatingGroup.create!([
  {tag_rating_groupable_id: 1, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 2, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 3, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 4, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 5, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 6, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 7, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 8, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 9, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 10, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 11, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 12, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 13, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 14, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 15, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 16, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 17, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 18, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 19, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 20, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 21, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 22, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 23, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 24, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 25, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 26, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 27, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 28, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 29, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 30, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 31, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 32, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 33, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 34, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 35, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 36, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 1, tag_rating_groupable_type: "Profile"},
  {tag_rating_groupable_id: 2, tag_rating_groupable_type: "Profile"},
  {tag_rating_groupable_id: 3, tag_rating_groupable_type: "Profile"},
  {tag_rating_groupable_id: 4, tag_rating_groupable_type: "Profile"},
  {tag_rating_groupable_id: 1, tag_rating_groupable_type: "Profile"},
  {tag_rating_groupable_id: 2, tag_rating_groupable_type: "Profile"},
  {tag_rating_groupable_id: 3, tag_rating_groupable_type: "Profile"},
  {tag_rating_groupable_id: 4, tag_rating_groupable_type: "Profile"},
  {tag_rating_groupable_id: 1, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 2, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 3, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 4, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 5, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 6, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 7, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 8, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 9, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 10, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 11, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 12, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 13, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 14, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 15, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 16, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 17, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 18, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 19, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 20, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 21, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 22, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 23, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 24, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 25, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 26, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 27, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 28, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 29, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 30, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 31, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 32, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 33, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 34, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 35, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 36, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 1, tag_rating_groupable_type: "SurveyResult"},
  {tag_rating_groupable_id: 2, tag_rating_groupable_type: "SurveyResult"},
  {tag_rating_groupable_id: 3, tag_rating_groupable_type: "SurveyResult"},
  {tag_rating_groupable_id: 4, tag_rating_groupable_type: "SurveyResult"},
  {tag_rating_groupable_id: 5, tag_rating_groupable_type: "SurveyResult"},
  {tag_rating_groupable_id: 6, tag_rating_groupable_type: "SurveyResult"},
  {tag_rating_groupable_id: 7, tag_rating_groupable_type: "SurveyResult"},
  {tag_rating_groupable_id: 1, tag_rating_groupable_type: "Profile"},
  {tag_rating_groupable_id: 2, tag_rating_groupable_type: "Profile"},
  {tag_rating_groupable_id: 3, tag_rating_groupable_type: "Profile"},
  {tag_rating_groupable_id: 4, tag_rating_groupable_type: "Profile"},
  {tag_rating_groupable_id: 1, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 2, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 3, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 4, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 5, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 6, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 7, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 8, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 9, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 10, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 11, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 12, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 13, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 14, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 15, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 16, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 17, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 18, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 19, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 20, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 21, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 22, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 23, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 24, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 25, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 26, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 27, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 28, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 29, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 30, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 31, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 32, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 33, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 34, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 35, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 36, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 1, tag_rating_groupable_type: "Offer"},
  {tag_rating_groupable_id: 1, tag_rating_groupable_type: "SurveyResult"},
  {tag_rating_groupable_id: 2, tag_rating_groupable_type: "SurveyResult"},
  {tag_rating_groupable_id: 3, tag_rating_groupable_type: "SurveyResult"},
  {tag_rating_groupable_id: 4, tag_rating_groupable_type: "SurveyResult"},
  {tag_rating_groupable_id: 5, tag_rating_groupable_type: "SurveyResult"},
  {tag_rating_groupable_id: 6, tag_rating_groupable_type: "SurveyResult"},
  {tag_rating_groupable_id: 7, tag_rating_groupable_type: "SurveyResult"},
  {tag_rating_groupable_id: 8, tag_rating_groupable_type: "SurveyResult"},
  {tag_rating_groupable_id: 9, tag_rating_groupable_type: "SurveyResult"},
  {tag_rating_groupable_id: 1, tag_rating_groupable_type: "Profile"},
  {tag_rating_groupable_id: 2, tag_rating_groupable_type: "Profile"},
  {tag_rating_groupable_id: 3, tag_rating_groupable_type: "Profile"},
  {tag_rating_groupable_id: 4, tag_rating_groupable_type: "Profile"},
  {tag_rating_groupable_id: 1, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 2, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 3, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 4, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 5, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 6, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 7, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 8, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 9, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 10, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 11, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 12, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 13, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 14, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 15, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 16, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 17, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 18, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 19, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 20, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 21, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 22, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 23, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 24, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 25, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 26, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 27, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 28, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 29, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 30, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 31, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 32, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 33, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 34, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 35, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 36, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 1, tag_rating_groupable_type: "SurveyResult"},
  {tag_rating_groupable_id: 2, tag_rating_groupable_type: "SurveyResult"},
  {tag_rating_groupable_id: 3, tag_rating_groupable_type: "SurveyResult"},
  {tag_rating_groupable_id: 4, tag_rating_groupable_type: "SurveyResult"},
  {tag_rating_groupable_id: 5, tag_rating_groupable_type: "SurveyResult"},
  {tag_rating_groupable_id: 6, tag_rating_groupable_type: "SurveyResult"},
  {tag_rating_groupable_id: 7, tag_rating_groupable_type: "SurveyResult"},
  {tag_rating_groupable_id: 8, tag_rating_groupable_type: "SurveyResult"},
  {tag_rating_groupable_id: 9, tag_rating_groupable_type: "SurveyResult"},
  {tag_rating_groupable_id: 1, tag_rating_groupable_type: "Offer"},
  {tag_rating_groupable_id: 2, tag_rating_groupable_type: "Offer"},
  {tag_rating_groupable_id: 3, tag_rating_groupable_type: "Offer"},
  {tag_rating_groupable_id: 37, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 38, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 39, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 40, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 41, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 42, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 43, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 44, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 45, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 46, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 47, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 48, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 49, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 50, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 51, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 52, tag_rating_groupable_type: "Choice"},
  {tag_rating_groupable_id: 4, tag_rating_groupable_type: "Offer"},
  {tag_rating_groupable_id: 5, tag_rating_groupable_type: "Offer"},
  {tag_rating_groupable_id: 6, tag_rating_groupable_type: "Offer"}
])


puts "Tags saved!"
