puts "> Creating neighborhoods........"

Neighborhood.create!([
  {title: "montorgueil", zone: 1},
  {title: "le marais", zone: 1},
  {title: "les halles", zone: 1},
  {title: "île de la cité", zone: 0},
  {title: "opera", zone: 0},
  {title: "île st. louis", zone: 1},
  {title: "grands boulevards", zone: 1},
  {title: "south pigalle", zone: 0},
  {title: "south pigalle", zone: 2},
  {title: "montmartre", zone: 2},
  {title: "place de clichy", zone: 2},
  {title: "abbesses", zone: 0},
  {title: "abbesses", zone: 2},
  {title: "gare du nord", zone: 2},
  {title: "la villette", zone: 0},
  {title: "la villette", zone: 2},
  {title: "republique", zone: 3},
  {title: "oberkampf", zone: 3},
  {title: "belleville", zone: 3},
  {title: "canal st. martin", zone: 3},
  {title: "bastille", zone: 3},
  {title: "nation", zone: 0},
  {title: "daumesnil", zone: 3},
  {title: "ménilmontant", zone: 3},
  {title: "nation", zone: 3},
  {title: "st. michel", zone: 4},
  {title: "quartier latin", zone: 4},
  {title: "odéon", zone: 0},
  {title: "montparnasse", zone: 4},
  {title: "odéon", zone: 4},
  {title: "denfert-rocherau", zone: 4},
  {title: "champs élysées", zone: 5},
  {title: "victor hugo", zone: 5},
  {title: "pereire", zone: 5},
  {title: "villiers", zone: 5},
  {title: "", zone: 0},
  {title: "ternes", zone: 0},
  {title: "ternes", zone: 5},
  {title: "", zone: 0},
  {title: "levallois", zone: 5},
  {title: "batignoles", zone: 0},
  {title: "batignoles", zone: 5},
  {title: "sur la seine ", zone: 1},
  {title: "les invalides ", zone: 1},
  {title: "BNF", zone: 0},
  {title: "BFM", zone: 3},
  {title: "saint-ouen", zone: 2},
  {title: "BNF", zone: 3},
  {title: "Clichy", zone: 2},
  {title: "Buttes chaumont", zone: 3},
  {title: "Bagnolet", zone: 2}
])

puts "Neightborhoods saved!"
