puts "> Creating equipments........"

EquipmentGroup.create!([
  {name: "Bar"},
  {name: "Cuisine"},
  {name: "Fumoir"},
  {name: "Internet"},
  {name: "Mobilier"},
  {name: "Services"},
  {name: "Son et Lumière"},
  {name: "Vidéo"}
])

Equipment.create!([
  {name: "agent de sécurité", equipment_group_id: 7},
  {name: "animateur", equipment_group_id: 7},
  {name: "barman", equipment_group_id: 7},
  {name: "canapés", equipment_group_id: 3},
  {name: "chafing-dishes", equipment_group_id: 1},
  {name: "chaises", equipment_group_id: 3},
  {name: "comptoir bar ", equipment_group_id: 2},
  {name: "congélateur", equipment_group_id: 1},
  {name: "connectique hdmi", equipment_group_id: 5},
  {name: "connectique jack", equipment_group_id: 4},
  {name: "connexion wifi disponible", equipment_group_id: 6},
  {name: "cuisinier", equipment_group_id: 7},
  {name: "dj", equipment_group_id: 7},
  {name: "désinstallation ", equipment_group_id: 7},
  {name: "ecran", equipment_group_id: 5},
  {name: "espace vestiaire", equipment_group_id: 3},
  {name: "four", equipment_group_id: 1},
  {name: "frigidaire bar", equipment_group_id: 2},
  {name: "frigidaire nourriture", equipment_group_id: 1},
  {name: "hôtesses d’accueil", equipment_group_id: 7},
  {name: "installation ", equipment_group_id: 7},
  {name: "lave vaisselle", equipment_group_id: 2},
  {name: "lave vaisselle", equipment_group_id: 1},
  {name: "lecteur dvd", equipment_group_id: 5},
  {name: "lumières piste", equipment_group_id: 4},
  {name: "machine à glaçons", equipment_group_id: 2},
  {name: "matériel animation", equipment_group_id: 3},
  {name: "matériel de barman", equipment_group_id: 2},
  {name: "micro-ondes", equipment_group_id: 1},
  {name: "micros", equipment_group_id: 4},
  {name: "ménage", equipment_group_id: 7},
  {name: "paravents", equipment_group_id: 3},
  {name: "personnel de bord", equipment_group_id: 7},
  {name: "photographe", equipment_group_id: 7},
  {name: "plaques de cuisson", equipment_group_id: 1},
  {name: "platines dj", equipment_group_id: 4},
  {name: "portier", equipment_group_id: 7},
  {name: "projectionniste", equipment_group_id: 7},
  {name: "régisseur", equipment_group_id: 7},
  {name: "rétroprojecteur", equipment_group_id: 5},
  {name: "serveurs", equipment_group_id: 7},
  {name: "stands de cuisson", equipment_group_id: 1},
  {name: "systèm son", equipment_group_id: 4},
  {name: "table de mixage", equipment_group_id: 4},
  {name: "tables basses", equipment_group_id: 3},
  {name: "tables de massage", equipment_group_id: 3},
  {name: "tables à manger", equipment_group_id: 3},
  {name: "tv", equipment_group_id: 5},
  {name: "un fumoir est à votre disposition", equipment_group_id: 8},
  {name: "ustensiles de cuisine", equipment_group_id: 1},
  {name: "vaisselle", equipment_group_id: 1},
  {name: "verrerie", equipment_group_id: 2},
  {name: "ça se passe dehors et le silence est de mise", equipment_group_id: 8}
])

puts "Equipments saved!"
