puts "> Creating items........"




Item.create!([
  {title: "Mini Clubs Pain Polaire - 30 pièces", section_id: 4, description: "<ul><li>Polaire, duxelle de champignons et crudités</li><li>Pain polaire, compotée d'oignons, chèvre et tomate confite</li><li>New-Yorkais ( pain polaire, pastrami, oignons rouges, cornichons aigre doux)</li></ul>", rank: 1, image_id: "8d12c97d835a620aaab66f8556e3db1a034874ab7e12df0c5f78245804d2"},
  {title: "Un hot dog avec tous ses condiments", section_id: 1, description: "<div>Notre Happhappeur arrive avec un son stand à hot-dog, sur lequel sont disposés les saucisses, le pain, les sauces et tous les condiments. <br>Reste plus qu'à confectionner votre hot dog en direct !! &nbsp;</div>", rank: 1, image_id: "02510bd1da531463e40b53b358ac1fa5e27052fc8058b8d85bb3a45186bc"},
  {title: "Comme à la maison sans les désagréments", section_id: 2, description: "Choisissez vos boissons pour l’open bar sur notre liste de courses, vous payez ce que vous consommez à petit prix. Notre personnel s’occupe de tout.<br><br>Tarif par heure. Merci d'indiquer le nombre d'heures souhaitées et de préciser les horaires dans le champs ci-dessous.", rank: 1, image_id: nil},
  {title: "Un cookie pour le dessert", section_id: 1, description: "Merci d'indiquer le nombre de cookies souhaités.", rank: 2, image_id: nil},
  {title: "Privatisez l’espace à moindre coût", section_id: 2, description: "L’espace reste privé uniquement pour vos convives. Le bar est ouvert avec les mêmes prix de consommations que dans le reste de l’établissement.<br><br>Exemples du prix des boissons : bière (4€), soft (5€), vin (5€), verre avec hard (8/10€), champagne (10/13€).<br><br>Forfait sur une base minimum de 4h. Si vous souhaitez profiter de cette option, merci de cocher la case !", rank: 2, image_id: nil},
  {title: "Brochettes - 40 pièces", section_id: 4, description: "<ul><li>Tomate, mozzarelle, basilic</li><li>Les 3 betteraves, huile d'olive à l'orange et ciboulette</li><li>Pain d'épices, edam, mimolette et bille de pomme</li><li>Ananas caramélisé, crevette et coriandre</li></ul>", rank: 2, image_id: nil},
  {title: "Saveurs d'hiver - 54 pièces", section_id: 4, description: "<ul><li>Risotto persillé aux champignons des bois</li><li>Sablé, Cube de poire, Fourme d'Ambert</li><li>Bressaola, purée de céleri truffée, brisures de châtaignes</li><li>Wroups aneth et coriandre, saumon fumé et crème de yuzu</li><li>Pain d'épices, edam, mimolette et bille de pomme</li><li>Mini mille feuille de pain d'épices, foie gras au thym</li></ul>", rank: 3, image_id: nil},
  {title: "All inclusive", section_id: 2, description: "<div>Vin et alcool fort à discrétion, laissez vous porter…<br><br>Prix par personne. Si vous souhaitez profiter de cette formule, merci d'indiquer le nombre de personnes prévues.&nbsp;<br>Sur une base minimum de 4h et 60 personnes.</div>", rank: 3, image_id: nil},
  {title: "Canapés - 54 pièces", section_id: 4, description: "<ul><li>Navet glacé au thym, sphère de potimarron, brisures de châtaignes et parmesan</li><li>Sablé, cube de cerise, foie gras de canard</li><li>Tortilla safranée de saumon à l'aneth</li><li>Risotto aux trois légumes</li><li>Crème de mais, volaille Tex Mex sur poivron rôti</li><li>Voile de riz printanière ( mangue, fruits de la passion ,crevette)</li><li>Petit choux au beaufort , noisettes et pistaches</li><li>Omelette au sésame</li><li>Bouton de courgette au curry, dîme inversé de carottes au gingembre</li></ul>", rank: 4, image_id: nil},
  {title: "Mignardises - 60 pièces", section_id: 4, description: "<ul><li>Cheese cake cassis</li><li>Palet au chocolat et miel d'acacia</li><li>Guimauve gourmande, confit de banane</li><li>Tarte crumble ananas et fruits de la passion</li><li>Tartelette façon \"Snickers\"</li><li>Caroline chocolat noir</li></ul>", rank: 5, image_id: nil},
  {title: "Tarif livraison", section_id: 4, description: "Pour Paris intra-muros :<br>Pour les autres zones, à définir avec votre Happhappeur.<br>", rank: 6, image_id: nil},
  {title: "Vous être entre 50 et 70 personnes ?", section_id: 3, description: "Sont inclus le ménage et un régisseur présent sur place.<br>", rank: nil, image_id: nil},
  {title: "Vous êtes moins de 50 personnes ?", section_id: 3, description: "Sont inclus le ménage et un régisseur présent sur place.", rank: nil, image_id: nil},
  {title: "Personnel de service", section_id: 7, description: "<div>Sur la base d'un maître d'hôtel pour 30 personnes et pour une vacation de 6h. Personnel de mise en place, de service et de débarassage.<br>Attention : les tarifs peuvent évoluer en fonction du lieu de réception et les contraintes qu'il peut imposer.<br></div>", rank: nil, image_id: nil},
  {title: "Les boissons", section_id: 6, description: "<b>Sur la base d'une bouteille pour 3 personnes.</b><br><ul><li>Chardonnay Viognier, Laurent Miquel : l'élégance et la fraîcheur du Chardonnay sont en parfaite harmonie avec les notes subtiles d'abricot et de pêche qui caractérisent le Viognier. L'association de ces deux cépages rend le vin frais, fruité, unique, une cuvée unique et originale.</li><li>Chateau du juge rouge, Cadillas : belle présentation avec une teinte rubis soutenue, surmontée d'un très léger reflet pourpre. De larges arômes frais, fruités, épicés et vanillés se dégagent au nez, accompagnés après aération de notes florales mentholées. Un vin fort, plaisant, alliant fraîcheur et subtilité.</li></ul><div></div><div><b>Les boissons non alcoolisées</b></div><div></div><ul><li>Sur la base d'une bouteille pour 8 personnes : Jus d'orange ou de pamplemouse frais pressés.&nbsp;</li><li>Sur la base d'une bouteille pour 5 personnes : Eaux minérales (Evian et San Pellegrino).</li></ul>", rank: nil, image_id: nil},
  {title: "Art de la table et logistique", section_id: 7, description: "<div><b>Le mobilier&nbsp;</b></div><ul><li>6 mètres de buffet</li><li>2 guéridons</li></ul><div><b>Art de la table</b></div><ul><li>Nappage en coton, couleur à valider</li><li>Assiette de présentation</li><li>Verrerie complète</li><li>Plateau de piste</li></ul><div><b>Equipement de l'office traiteur</b></div><ul><li>Échelles de dressage des produits alimentaires</li><li>Consommables (housses isothermes, sacs poubelle)</li><li>Matériel de remise en température.</li></ul>", rank: nil, image_id: nil},
  {title: "Le cocktail", section_id: 5, description: "<div><b>Cocktail en équivalence de 22 pièces, composé comme suit :</b><br><ul><li>Pièces salées</li><li>1 mini plat chaud (équivalence de 4 pièces)</li><li>Pièces sucrées</li></ul>Merci d'indiquer le nombre d'invités.</div><div>De 50 à 100 personnes : 81 € par personne.</div><div>A partir de 100 personnes : 70 € par personne.&nbsp;</div><div><br></div><div>Voici un exemple de gastronomie :</div><div><br></div><div><b>Les pièces salées</b><br></div><ul><li>Millefeuille sucré-salé à la mangue et à la Tomme de Savoie</li><li>Mille-feuille d'anguille, foie gras et poireaux, gelée de genépi</li><li>Pain d'épices, bille de pomme granny, edam &amp; mimolette</li><li>Roulée de courgette, beurre noix de cajou</li><li>Finger, &nbsp;Rhubarbe romarin, céleri branche, abricot</li><li>Finger: fondue de poireaux, oeuf de caille</li><li>Pain de mie, confiture de coings, comté</li><li>Pain polaire, pastrami, oignons rouges, cornichons aigre doux</li><li>Croustade Mousseux forestier et crumble de mendiant</li><li>Croustade Concassée de giroles à l'huile de noisette</li><li>Clafoutis tomate cerise et beaufort</li><li>Clafoutis foie gras et cerise</li><li>Carotte rouge, fromage de Beaufort, saucisse fumée, crème de ciboule</li><li>Petit choux au beaufort , noisettes et pistaches</li><li>Pince Viande de grison, parmesan, roquette</li></ul><div><br></div><div><b>Les mini plats chauds</b><br>En équivalence de 4 pièces. Servis dans une boite en pin. 1 pièce au choix par personne.&nbsp;</div><ul><li>Risotto de Crozet, tomme de Savoie et viande de grison</li><li>Tartiflette</li><li>Croziflette au miel</li></ul><div><br></div><div><b>Les pièces sucrées</b><br></div><ul><li>Le mont-blanc</li><li>Religieuse aux myrtilles</li><li>Tartelette Mirabelles et chartreuse</li><li>Gâteau de Savoie aux noix</li><li>Tartelette de vin chaud, crème légère à la cannelle</li><li>Dame de chocolat au lait et myrtilles</li><li>Sucette de gâteau de Savoie aux myrtilles sauvages</li><li>Palet au chocolat et miel d?acacia</li><li>Tartelette orange et figue aux noix</li><li>Moelleux chocolat &amp; &nbsp;poire</li><li>Tatin aux quatre baies, crème d'Isigny</li></ul>", rank: nil, image_id: nil},
  {title: "Le cocktail", section_id: 8, description: "Merci d'indiquer le nombre d'invités.&nbsp;<br>De 50 à 100 personnes : 74 € par personne.<br>à partir de 100 personnes : 63 € par personne.&nbsp;<br><br>Voici un exemple de gastronomie :<br><br><b>Les pièces salées</b><br><br><b>Les voiles de riz</b><br><ul><li>Magret de canard, crème de roquette et pétale de betterave</li><li>Crevette et coriandre, pétale de mangue fraîche</li></ul><b>Les brochettes</b><br><ul><li>Pain d'épices, bille de pomme granny, edam &amp; mimolette</li><li>Thon fumé à l'huile de noisette, pamplemousse &amp; persil plat</li></ul><b>Les fingers<br></b><ul><li>Tomate façon pissaladière</li><li>Shiitake</li></ul><b>Mini clubs</b><br><ul><li>Pain polaire, compotée d'oignons, chèvre et tomate confite</li><li>New-Yorkais (pain polaire, pastrami, oignons rouges, cornichons aigre doux)</li></ul><b>Les souvenirs de voyages</b><br><ul><li>Roulé de courgette, mousseline de cajou et sphère d'huile d'olive</li><li>Omelette au sésame, saumon label rouge et soja frais</li><li>Crème de maïs et volaille tex-mex sur poivron rôti</li></ul><b>Tendances salées<br></b><ul><li>Navet glacé au thym, sphère de potimarron, brisures de parmesan</li><li>Bressaola, purée de céleri truffée, brisures de châtaignes</li></ul><b>Les Risotto<br></b><ul><li>White risotto: Champignon persillé</li><li>Risotto aux trois légumes</li></ul><b>Fraîcheurs</b><br><ul><li>Pince de betterave chioggia</li><li>saumon fumé</li><li>pomme Spirale de courgette et carotte</li><li>radis et beaufort</li></ul><b>Tortillas</b><br><ul><li>Tortilla tex-mex de chorizo et petits pois</li><li>Tortilla tex-mex de jambon Serrano et tomate confite</li></ul><b>Les carolines</b><br><ul><li>Foie gras et caramel salé</li><li>Saumon mariné à l'aneth</li></ul><br><b>Les mini plats chauds</b><br>(en équivalence de 4 pièces) : 1 pièce au choix. Servis dans une boite en pin.<br><ul><li>Filet de volaille rôtie, risotto de Crozet au parmesan</li><li>Saint-Jacques poêlée au sésame wasabi, fondue de chicons braisées</li><li>Jarret de veau braisé, céleri et pomme grenailles rôties</li><li>Dos de cabillaud rôti, spaghettis de courgettes et crème de crevettes</li></ul><br><span><b>Les pièces sucrées</b>&nbsp;</span><br><br><b>Les tartelettes</b><br><ul><li>Citron et yuzu</li><li>Chocolat pure origine</li><li>Cassis passion</li></ul><b>La farandole des cheese-cake</b><br><ul><li>Cassis</li><li>Abricot</li></ul><b>La folie des choux</b><br><ul><li>Mangue passion</li><li>Pistache</li><li>Citron</li></ul><b>Les traditions</b><br><ul><li>Guimauve gourmande, éclat de coco et confit de banane</li><li>Quenelle de citron vert, sablé crumble</li></ul><b>Les folie's<br></b><ul><li>Coque chocolat, jus d'orange et fraise fraîche façon macaron</li><li>Palet au chocolat et miel d'acacia</li><li>Crumble inversé, gelée de framboise et ibiscus</li><li>Choux façon carambar</li><li>Praliné de Montélimar et dôme de chocolat intense</li></ul>", rank: nil, image_id: nil}
])




puts "Items saved!"
