puts "> Creating surveys........"



Survey.create!([
  {user_id: nil, questionnaire_id: 1, step: 9, event_name: nil, person_name: nil},
  {user_id: nil, questionnaire_id: 1, step: 9, event_name: nil, person_name: nil},
  {user_id: nil, questionnaire_id: 1, step: 9, event_name: nil, person_name: nil},
  {user_id: nil, questionnaire_id: 1, step: 9, event_name: nil, person_name: nil},
  {user_id: nil, questionnaire_id: 1, step: 9, event_name: nil, person_name: nil},
  {user_id: nil, questionnaire_id: 1, step: 9, event_name: nil, person_name: nil},
  {user_id: nil, questionnaire_id: 1, step: 9, event_name: nil, person_name: nil},
  {user_id: nil, questionnaire_id: 1, step: 9, event_name: nil, person_name: nil},
  {user_id: nil, questionnaire_id: 1, step: 9, event_name: nil, person_name: nil},
  {user_id: nil, questionnaire_id: 1, step: 1, event_name: nil, person_name: nil},
  {user_id: nil, questionnaire_id: 1, step: 1, event_name: nil, person_name: nil},
  {user_id: nil, questionnaire_id: 1, step: 1, event_name: nil, person_name: nil}
])
SurveyResult.create!([
  {survey_id: 1},
  {survey_id: 2},
  {survey_id: 3},
  {survey_id: 4},
  {survey_id: 5},
  {survey_id: 6},
  {survey_id: 7},
  {survey_id: 8},
  {survey_id: 9}
])

Answer.create!([
  {survey_id: 1, choice_id: 3},
  {survey_id: 1, choice_id: 8},
  {survey_id: 1, choice_id: 11},
  {survey_id: 1, choice_id: 14},
  {survey_id: 1, choice_id: 14},
  {survey_id: 1, choice_id: 18},
  {survey_id: 1, choice_id: 23},
  {survey_id: 1, choice_id: 31},
  {survey_id: 1, choice_id: 35},
  {survey_id: 2, choice_id: 4},
  {survey_id: 2, choice_id: 7},
  {survey_id: 2, choice_id: 11},
  {survey_id: 2, choice_id: 16},
  {survey_id: 2, choice_id: 16},
  {survey_id: 2, choice_id: 17},
  {survey_id: 2, choice_id: 24},
  {survey_id: 2, choice_id: 30},
  {survey_id: 2, choice_id: 35},
  {survey_id: 3, choice_id: 2},
  {survey_id: 3, choice_id: 7},
  {survey_id: 3, choice_id: 11},
  {survey_id: 3, choice_id: 16},
  {survey_id: 3, choice_id: 16},
  {survey_id: 3, choice_id: 17},
  {survey_id: 3, choice_id: 23},
  {survey_id: 3, choice_id: 29},
  {survey_id: 3, choice_id: 35},
  {survey_id: 4, choice_id: 1},
  {survey_id: 4, choice_id: 7},
  {survey_id: 4, choice_id: 9},
  {survey_id: 4, choice_id: 13},
  {survey_id: 4, choice_id: 13},
  {survey_id: 4, choice_id: 18},
  {survey_id: 4, choice_id: 21},
  {survey_id: 4, choice_id: 29},
  {survey_id: 4, choice_id: 35},
  {survey_id: 5, choice_id: 2},
  {survey_id: 5, choice_id: 7},
  {survey_id: 5, choice_id: 10},
  {survey_id: 5, choice_id: 14},
  {survey_id: 5, choice_id: 14},
  {survey_id: 5, choice_id: 18},
  {survey_id: 5, choice_id: 24},
  {survey_id: 5, choice_id: 32},
  {survey_id: 5, choice_id: 36},
  {survey_id: 6, choice_id: 2},
  {survey_id: 6, choice_id: 6},
  {survey_id: 6, choice_id: 11},
  {survey_id: 6, choice_id: 16},
  {survey_id: 6, choice_id: 16},
  {survey_id: 6, choice_id: 17},
  {survey_id: 6, choice_id: 24},
  {survey_id: 6, choice_id: 31},
  {survey_id: 6, choice_id: 36},
  {survey_id: 7, choice_id: 3},
  {survey_id: 7, choice_id: 8},
  {survey_id: 7, choice_id: 12},
  {survey_id: 7, choice_id: 16},
  {survey_id: 7, choice_id: 16},
  {survey_id: 7, choice_id: 18},
  {survey_id: 7, choice_id: 22},
  {survey_id: 7, choice_id: 31},
  {survey_id: 7, choice_id: 36},
  {survey_id: 8, choice_id: 3},
  {survey_id: 8, choice_id: 5},
  {survey_id: 8, choice_id: 10},
  {survey_id: 8, choice_id: 15},
  {survey_id: 8, choice_id: 15},
  {survey_id: 8, choice_id: 18},
  {survey_id: 8, choice_id: 24},
  {survey_id: 8, choice_id: 30},
  {survey_id: 8, choice_id: 35},
  {survey_id: 9, choice_id: 2},
  {survey_id: 9, choice_id: 6},
  {survey_id: 9, choice_id: 10},
  {survey_id: 9, choice_id: 13},
  {survey_id: 9, choice_id: 13},
  {survey_id: 9, choice_id: 18},
  {survey_id: 9, choice_id: 24},
  {survey_id: 9, choice_id: 30},
  {survey_id: 9, choice_id: 35}
])


puts "Surveys saved!"
